/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Ahmad Pudoli
 */
public class MenuUtama extends javax.swing.JFrame {

    MasterPelanggan formMasterPelanggan = new MasterPelanggan();
    MasterKategoriBarang formMasterKategoriBarang = new MasterKategoriBarang();
    MasterBarang formMasterBarang = new MasterBarang();
    TransaksiPesanan formTransaksiPesanan = new TransaksiPesanan();
    CetakLapPesanan formCetakLapPesanan = new CetakLapPesanan();
    
    /**
     * Creates new form MenuUtama
     */
      
    public MenuUtama() {
        initComponents();
        this.setSize(600, 500);     
        setLocationRelativeTo(this);
        Koneksi.Database.KoneksiDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        MMenu = new javax.swing.JMenu();
        MPelanggan = new javax.swing.JMenuItem();
        MKategori = new javax.swing.JMenuItem();
        MBarang = new javax.swing.JMenuItem();
        MTransaksi = new javax.swing.JMenu();
        TBuktiPesan = new javax.swing.JMenuItem();
        MLaporan = new javax.swing.JMenu();
        LPelanggan = new javax.swing.JMenuItem();
        LBarang = new javax.swing.JMenuItem();
        LPesanan = new javax.swing.JMenuItem();
        MExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MMenu.setText("File Master");

        MPelanggan.setText("Entry Data Pelanggan");
        MPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPelangganActionPerformed(evt);
            }
        });
        MMenu.add(MPelanggan);

        MKategori.setText("Entry Data Kategori");
        MKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MKategoriActionPerformed(evt);
            }
        });
        MMenu.add(MKategori);

        MBarang.setText("Entry Data Barang");
        MBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MBarangActionPerformed(evt);
            }
        });
        MMenu.add(MBarang);

        jMenuBar.add(MMenu);

        MTransaksi.setText("Transaksi");

        TBuktiPesan.setText("Bukti Pesanan");
        TBuktiPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBuktiPesanActionPerformed(evt);
            }
        });
        MTransaksi.add(TBuktiPesan);

        jMenuBar.add(MTransaksi);

        MLaporan.setText("Laporan");

        LPelanggan.setText("Laporan Data Pelanggan");
        MLaporan.add(LPelanggan);

        LBarang.setText("Laporan Data Barang");
        MLaporan.add(LBarang);

        LPesanan.setText("Laporan Pesanan");
        LPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LPesananActionPerformed(evt);
            }
        });
        MLaporan.add(LPesanan);

        jMenuBar.add(MLaporan);

        MExit.setText("Exit Program");
        MExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MExitMouseClicked(evt);
            }
        });
        jMenuBar.add(MExit);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MBarangActionPerformed
        // TODO add your handling code here:
        formMasterBarang.setVisible(true);
        formMasterBarang.setLocationRelativeTo(this);
        formMasterBarang.controller.reset();
        formMasterBarang.controller.isiTable();
    }//GEN-LAST:event_MBarangActionPerformed

    private void MExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MExitMouseClicked

    private void MPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPelangganActionPerformed
        formMasterPelanggan.setVisible(true);
        formMasterPelanggan.setLocationRelativeTo(this);
        formMasterPelanggan.controller.reset();
        formMasterPelanggan.controller.isiTable();
    }//GEN-LAST:event_MPelangganActionPerformed

    private void MKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MKategoriActionPerformed
        formMasterKategoriBarang.setVisible(true);
        formMasterKategoriBarang.setLocationRelativeTo(this);
        formMasterKategoriBarang.controller.reset();
        formMasterKategoriBarang.controller.isiTable();
    }//GEN-LAST:event_MKategoriActionPerformed

    private void TBuktiPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBuktiPesanActionPerformed
        formTransaksiPesanan.setVisible(true);
        formTransaksiPesanan.setLocationRelativeTo(this);
        formTransaksiPesanan.controller.resetFormPesanan();
    }//GEN-LAST:event_TBuktiPesanActionPerformed

    private void LPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LPesananActionPerformed
        formCetakLapPesanan.setVisible(true);
        formCetakLapPesanan.setLocationRelativeTo(this);
        formCetakLapPesanan.controller.awal();
    }//GEN-LAST:event_LPesananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LBarang;
    private javax.swing.JMenuItem LPelanggan;
    private javax.swing.JMenuItem LPesanan;
    private javax.swing.JMenuItem MBarang;
    private javax.swing.JMenu MExit;
    private javax.swing.JMenuItem MKategori;
    private javax.swing.JMenu MLaporan;
    private javax.swing.JMenu MMenu;
    private javax.swing.JMenuItem MPelanggan;
    private javax.swing.JMenu MTransaksi;
    private javax.swing.JMenuItem TBuktiPesan;
    private javax.swing.JMenuBar jMenuBar;
    // End of variables declaration//GEN-END:variables
}
